### PR TITLE
PG-bugfix-0011 Donations: CRA list Pagination displayed outside the frame

### PR DESCRIPTION
**Pull request by techmusicmoney**
Pagination overlapping in charity selector. 

[[Video]()](https://bcgov.sharepoint.com/teams/02365/_layouts/15/stream.aspx?id=%2Fteams%2F02365%2FShared%20Documents%2FGreenfield%20Backlog%2FTesting%2FSteffi%2DTesting%2FScreen%20Recording%202023%2D04%2D24%20at%2011%2E30%2E01%20AM%2Emov)

### CODE REVIEW

**Review by jp-Telus — COMMENTED** [review]
Hi Paul,

Just want to clarify, why the new blade file "resources/views/pagination/custom.blade.php" created on the new folder "resources/views/pagination"? This new blade is only used in the existing blade file "resources/views/volunteering/partials/organizations.blade.php",  why this new blade is not group into the "resources/views/volunteering/partials/" ? 

Thank you.

**Comment by techmusicmoney** [comment]
> Hi Paul,
> 
> Just want to clarify, why the new blade file "resources/views/pagination/custom.blade.php" created on the new folder "resources/views/pagination"? This new blade is only used in the existing blade file "resources/views/volunteering/partials/organizations.blade.php", why this new blade is not group into the "resources/views/volunteering/partials/" ?
> 
> Thank you.

Hey James, 

My rationale is the pagination could be used anywhere in the app in the future so I did not want to tie it into one specific folder in the event we needed to use it somewhere else later? Thoughts?

**Comment by jp-Telus** [comment]
> organizations

Hi Paul,

This pagination 

> > Hi Paul,
> > Just want to clarify, why the new blade file "resources/views/pagination/custom.blade.php" created on the new folder "resources/views/pagination"? This new blade is only used in the existing blade file "resources/views/volunteering/partials/organizations.blade.php", why this new blade is not group into the "resources/views/volunteering/partials/" ?
> > Thank you.
> 
> Hey James,
> 
> My rationale is the pagination could be used anywhere in the app in the future so I did not want to tie it into one specific folder in the event we needed to use it somewhere else later? Thoughts?

Hi Paul, 

since you have already sharing the same program of charity selection pages on multiple area but you didn't have a separate folder for that, I thought we don't need this particular portion to be separated for other area. unless you have storing reason for only this portion. I prefer to group all related program together. Thank you,

James

**Comment by techmusicmoney** [comment]
Hey James, 

My rationale is to keep things dry as possible. D.ont R. epeat Y.ourself. Pagination can be used in theory on any model and is abstract enough to be used many times. The charity selector is used in a few places and varies depending on where its used so its different. If we have the same feature defined in multiple places thats another issue we should probably look at solving. For instance in some places charity selector allows 1 charity in some places 10 so its not the same everywhere which is why we might have went the route we did in the past as we were developing it and figuring out what it would be how it would be used around the site. Pagination is a little more straightforward to see it can be reused anywhere. I made the change you suggested. Its your call.

**Review by jp-Telus — APPROVED** [review]

**Pull request merged**
