### PR TITLE
[TEST][jz-016]eForm 'PECSF ID' to be populated for Gaming and Fundraising Events

### PR DESCRIPTION
**Pull request by jizhaogit**
1. removed the debug information
2. enable some UX js on volunteering->eForm page.

### CODE REVIEW

**Review by jp-Telus — APPROVED** [review]
Approved. 

Quick question, are you develop a script to assign the PECSF ID on existing event pledges? Thanks

**Comment by jizhaogit** [comment]
no i didn't do the existing code modification. the new PECSF ID is only be generated when "create" a new donation.

**Comment by jp-Telus** [comment]
> no i didn't do the existing code modification. the new PECSF ID is only be generated when "create" a new donation.

Hi Ji,

We need to fix the existing event pledges in Production. Any suggestion? 

Thank you.

**Comment by jizhaogit** [comment]
i can think about the following steps:
1. prepare a SQL statement to generate all duplicated PECSF ID grouped in different prefix code. 
2. modify the later item with a new PECSF ID which is prefix code plus date number that we run the script plus "001" . If there are more than 1 repeats, it could be "002", "003", etc.

Please let me know what your thinking. thanks

**Pull request merged**
